project:
  type: website
  output-dir: docs
  resources: ["requirements.txt"]

website:
  title: "Coding Cheatsheets with Kasjan"
  repo-url: https://github.com/kasjansmigielski/coding-cheatsheets
  repo-branch: main
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Cheatsheets"
        menu:
          - text: "Python Basics"
            href: cheatsheets/01-python-basics.qmd
          - text: "Pandas Filtering"
            href: cheatsheets/02-pandas-filtering.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    code-tools: true
    code-fold: false
    code-summary: "Pokaż kod"
    code-line-numbers: false
    include-in-header:
      - text: |
          <script src="https://unpkg.com/thebelab@latest"></script>
          <script>
            thebelab.bootstrap({
              requestKernel: true,
              binderOptions: {
                repo: "kasjansmigielski/coding-cheatsheets",
                ref: "main"
              },
              kernelOptions: {
                name: "python3"
              },
              codeMirrorConfig: {
                theme: "default"
              }
            });
          </script>
execute:
  echo: true
  warning: false
  message: false
  freeze: auto