project:
  type: website
  output-dir: docs
  resources: ["requirements.txt"]

website:
  title: "Coding Cheatsheets with Kasjan"
  repo-url: https://github.com/kasjansmigielski/coding-cheatsheets
  repo-branch: main
  repo-actions: [source]
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Cheatsheets"
        menu:
          - text: "Python Basics"
            href: cheatsheets/01-python-basics.qmd
          - text: "Pandas Filtering"
            href: cheatsheets/02-pandas-filtering.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    code-tools: true
    thebe:
      repo: kasjansmigielski/coding-cheatsheets   # jawnie: skąd Binder ma brać kod
      branch: main
      kernelName: python3
execute:
  echo: true
  warning: false
  message: false
  freeze: auto